name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: edUjolleuj9Qc2XkbCdQrELiS5eKuNwu
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Unit Tests
        run: yarn test --watchAll=false
      - name: E2E Tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
